"""
build_remaining_serials.py

Builds the ordered serial list for every Aisle A tag that has NOT yet
been shipped (Batches 1 + 2), in the client's requested sequential order:

    for each bay in A6 .. A26:
        for each row in 1, 2, 3, 4:
            for each column in A, B, C, D, E, G, H, J, K, L:
                if the serial exists in COMPLETE_SOLUTION
                and was not in Batch 1 or Batch 2:
                    add it

Serials that don't exist in COMPLETE_SOLUTION (row-3/4 K,L, and the 4
known anomalies) are naturally skipped. Output: one serial per line
ready for `generate_batch.py --serials`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

COLUMNS_ORDER = ["A", "B", "C", "D", "E", "G", "H", "J", "K", "L"]
ROWS_ORDER = [1, 2, 3, 4]


def load_shipped_serials(first_csv: Path, second_serials: Path) -> set[str]:
    shipped = set(pd.read_csv(first_csv)["Serial"].astype(str))
    for line in second_serials.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            shipped.add(s)
    return shipped


def build_ordered_remaining(
    complete_csv: Path, shipped: set[str], bay_start: int, bay_end: int
) -> list[str]:
    df = pd.read_csv(complete_csv)
    known = set(df["serial"].astype(str))

    ordered: list[str] = []
    for bay in range(bay_start, bay_end + 1):
        for row in ROWS_ORDER:
            for col in COLUMNS_ORDER:
                serial = f"A{bay}-{row}{col}"
                if serial in known and serial not in shipped:
                    ordered.append(serial)
    return ordered


def main(argv: list[str] | None = None) -> int:
    here = Path(__file__).resolve().parent
    inputs = here.parent / "inputs"
    default_output = inputs / "batch-03.serials.txt"

    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--complete", type=Path, default=inputs / "COMPLETE_SOLUTION_ALL_52_PAGES.csv")
    p.add_argument("--first-matched", type=Path, default=inputs / "FIRST_100_TAGS_MATCHED.csv")
    p.add_argument("--second-serials", type=Path, default=inputs / "batch-02.serials.txt")
    p.add_argument("--bay-start", type=int, default=6)
    p.add_argument("--bay-end", type=int, default=26)
    p.add_argument("--output", type=Path, default=default_output)
    args = p.parse_args(argv)

    shipped = load_shipped_serials(args.first_matched, args.second_serials)
    remaining = build_ordered_remaining(args.complete, shipped, args.bay_start, args.bay_end)

    header = (
        "# Client-ordered remaining-Aisle-A serials (sequential within each bay).\n"
        "# Auto-generated by build_remaining_serials.py — do not hand-edit.\n"
        f"# Bays {args.bay_start}..{args.bay_end}, excluding all serials shipped in Batch 1 + Batch 2.\n"
        f"# Order per bay: row 1 A..L, row 2 A..L, row 3 A..J (no K,L), row 4 A..J.\n"
        f"# Total serials: {len(remaining)}\n"
        "\n"
    )
    args.output.write_text(header + "\n".join(remaining) + "\n", encoding="utf-8")

    print(f"Shipped serials (Batch 1 + 2): {len(shipped)}")
    print(f"Remaining serials ordered:     {len(remaining)}")
    print(f"  first 10: {remaining[:10]}")
    print(f"  last  10: {remaining[-10:]}")
    print(f"Wrote: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
